<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_content',
		'title' => 'Content',
		'fields' => array (
			array (
				'key' => 'field_548bd2b68d3c7',
				'label' => 'Section',
				'name' => 'section',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_548bd3288d3c8',
						'label' => 'Context',
						'name' => 'context',
						'type' => 'wysiwyg',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_548bd3698d3c9',
						'label' => 'Photo',
						'name' => 'photo',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'package',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_package-detail',
		'title' => 'Package Detail',
		'fields' => array (
			array (
				'key' => 'field_548bf6941f467',
				'label' => 'Tour Package',
				'name' => 'tour_package',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'package',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_548bf6c81f469',
				'label' => 'Tour Start',
				'name' => 'tour_start',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'M d, yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_548bf6e41f46a',
				'label' => 'Tour End',
				'name' => 'tour_end',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'M d, yy',
				'first_day' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'booking',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_payment',
		'title' => 'Payment',
		'fields' => array (
			array (
				'key' => 'field_548bfe3f31e2d',
				'label' => 'Detail',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_548bfe0431e2a',
				'label' => 'Payment Method',
				'name' => 'payment_method',
				'type' => 'select',
				'choices' => array (
					'Angel Gateway' => 'Angel Gateway',
				),
				'default_value' => 'Angel Gateway',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_548bfe2031e2b',
				'label' => 'Total Amount',
				'name' => 'total_amount',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe3031e2c',
				'label' => 'Paid Amount',
				'name' => 'paid_amount',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe4731e2e',
				'label' => 'Billing Address',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_548bfe5331e2f',
				'label' => 'Full Name',
				'name' => 'full_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe5c31e30',
				'label' => 'Address 1',
				'name' => 'address_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe6431e31',
				'label' => 'Address 2',
				'name' => 'address_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe6b31e32',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe7131e33',
				'label' => 'State',
				'name' => 'state',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe7831e34',
				'label' => 'Zipcode',
				'name' => 'zipcode',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bfe7e31e35',
				'label' => 'Country',
				'name' => 'country',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'booking',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_detail',
		'title' => 'Detail',
		'fields' => array (
			array (
				'key' => 'field_548bf86fc4d5c',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_548bf882cca5a',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bf882c4d5d',
				'label' => 'Price',
				'name' => 'price',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548bf88dc4d5e',
				'label' => 'Tour Type',
				'name' => 'tour_type',
				'type' => 'select',
				'choices' => array (
					'Private Tour' => 'Private Tour',
					'Group Tour' => 'Group Tour',
				),
				'default_value' => 'Private Tour',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_548bf8b9c4d5f',
				'label' => 'Maximum Person',
				'name' => 'maximum_person',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_548bf88dc4d5e',
							'operator' => '==',
							'value' => 'Group Tour',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_548bf8cfc4d60',
				'label' => 'Schedule',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_548bf8dbc4d61',
				'label' => 'Tour Schedule',
				'name' => 'tour_schedule',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_548bf8e7c4d62',
						'label' => 'Tour Start',
						'name' => 'tour_start',
						'type' => 'date_picker',
						'column_width' => 50,
						'date_format' => 'yymmdd',
						'display_format' => 'M d, yy',
						'first_day' => 0,
					),
					array (
						'key' => 'field_548bf90bc4d63',
						'label' => 'Tour End',
						'name' => 'tour_end',
						'type' => 'date_picker',
						'column_width' => 50,
						'date_format' => 'yymmdd',
						'display_format' => 'M d, yy',
						'first_day' => 0,
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Schedule',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'package',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_booking-status',
		'title' => 'Booking Status',
		'fields' => array (
			array (
				'key' => 'field_548bfc5113919',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'select',
				'instructions' => 'Not Showing = booked, paid, traveler not show up
	Complete = booked, paid, traveler finished trip',
				'required' => 1,
				'choices' => array (
					'New' => 'New',
					'Available' => 'Available',
					'Paid' => 'Paid',
					'Cancelled' => 'Cancelled',
					'Not Show Up' => 'Not Show Up',
					'Complete' => 'Complete',
				),
				'default_value' => 'New',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'booking',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_overview',
		'title' => 'Overview',
		'fields' => array (
			array (
				'key' => 'field_548cbf4a08658',
				'label' => 'Cover',
				'name' => 'cover',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_548cbf5708659',
				'label' => 'Overview',
				'name' => 'overview',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'package',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


?>